Repository future-architect/uroborosql, pull requests merged in 2018-03, with the labels that each got.

#109 Fixed a problem that SecretResultSet#close caused NullPointerException
  src/main/java/jp/co/future/uroborosql/filter/SecretResultSet.java
  src/test/java/jp/co/future/uroborosql/filter/SecretResultSetTest.java
Labels: bug

#112 Fixed not to output bind parameter comment when procedure call
  src/main/java/jp/co/future/uroborosql/AbstractAgent.java
  src/main/java/jp/co/future/uroborosql/SqlAgentImpl.java
  src/main/java/jp/co/future/uroborosql/node/BindVariableNode.java
  src/main/java/jp/co/future/uroborosql/node/ParenBindVariableNode.java
  src/main/java/jp/co/future/uroborosql/parameter/OutParameter.java
  src/main/java/jp/co/future/uroborosql/parser/SqlParserImpl.java
  src/test/java/jp/co/future/uroborosql/SqlAgentTest.java
Labels: bug

#113 I would like ResultSetConverter to convert CLOB, BLOB, and Array to a manageable type instead of getting it as an object
  src/main/java/jp/co/future/uroborosql/converter/MapResultSetConverter.java
  src/test/java/jp/co/future/uroborosql/converter/EntityResultSetConverterTest.java
  src/test/java/jp/co/future/uroborosql/converter/MapResultSetConverterTest.java
Labels: improvement

#115 fix #114 SqlAgent#close() commit/rollback before Connection#close()
  src/main/java/jp/co/future/uroborosql/tx/LocalTransactionContext.java
  src/main/java/jp/co/future/uroborosql/tx/LocalTransactionManager.java
Labels: bug

#116 EntityHandler add emptyStringEqualsNull property
  src/main/java/jp/co/future/uroborosql/mapping/DefaultEntityHandler.java
  src/main/java/jp/co/future/uroborosql/mapping/EntityHandler.java
  src/test/java/jp/co/future/uroborosql/mapping/DefaultEntityHandlerTest.java
Labels: enhancement
