Repository future-architect/uroborosql, pull requests merged in 2019-01, with the labels that each got.

#142 In NioSqlManager, Add the presence or absence of the specified file monitoring
  REPL/repl.properties
  src/main/java/jp/co/future/uroborosql/client/SqlREPL.java
  src/main/java/jp/co/future/uroborosql/store/NioSqlManagerImpl.java
  src/test/java/jp/co/future/uroborosql/store/NioSqlManagerTest.java
Labels: enhancement

#143 Changed to `SqlBatch#paramStream` to accept beans stream
  src/main/java/jp/co/future/uroborosql/SqlBatchImpl.java
  src/main/java/jp/co/future/uroborosql/fluent/SqlBatch.java
  src/main/java/jp/co/future/uroborosql/utils/BeanAccessor.java
  src/test/java/jp/co/future/uroborosql/SqlAgentTest.java
  src/test/resources/sql/example/insert_product_for_bean.sql
Labels: enhancement

#144 Fixed an issue where `.queryWith("...").stream().map(r -> r).iterator()` caused an error.
  src/main/java/jp/co/future/uroborosql/SqlAgentImpl.java
  src/test/java/jp/co/future/uroborosql/Issue141Test.java
Labels: bug

#146 fix javadoc comments
  src/main/java/jp/co/future/uroborosql/AbstractAgent.java
  src/main/java/jp/co/future/uroborosql/enums/InsertsType.java
  src/main/java/jp/co/future/uroborosql/mapping/EntityHandler.java
Labels: invalid

#149 add SqlFluent#sqlId() and testcase
  pom.xml
  src/main/java/jp/co/future/uroborosql/AbstractSqlFluent.java
  src/main/java/jp/co/future/uroborosql/context/SqlContextImpl.java
  src/main/java/jp/co/future/uroborosql/fluent/SqlFluent.java
  src/test/java/jp/co/future/uroborosql/AbstractSqlFluentTest.java
  src/test/java/jp/co/future/uroborosql/context/SqlContextImplTest.java
Labels: enhancement

#150 Add SqlFluent#param(String, Supplier)
  src/main/java/jp/co/future/uroborosql/AbstractSqlFluent.java
  src/main/java/jp/co/future/uroborosql/context/SqlContextImpl.java
  src/main/java/jp/co/future/uroborosql/fluent/SqlFluent.java
  src/test/java/jp/co/future/uroborosql/AbstractSqlFluentTest.java
Labels: enhancement
